### ISSUE TITLE
Additions: smaller TTF version, and individual-letter/subset font version

### ISSUE THREAD

**Issue by gwern** [TeX-Live/yinit#1]
While adding drop caps to [my website](https://www.gwern.net) recently ([demo](https://twitter.com/gwern/status/1102279254652407808)), I came across `yinit` and we really wanted to use it. However, the TTF/OTF file is quite large, and it would be too expensive to have it downloaded on every page for a single drop caps.

So Obormot converted the OTF to [a TTF version](http://share.obormot.net/misc/gwern/Yinit.ttf) (uncompressed: 699KB->168KB) which is much smaller.

Then  he subsetted the font in FontForge, creating a [package of individual font files](https://share.obormot.net/misc/gwern/drop_caps_fonts.zip), which permits loading *only* the letter used on each page with the following example CSS (update paths as relevant):

```css
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-A.ttf') format('truetype');
    unicode-range: U+0041;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-B.ttf') format('truetype');
    unicode-range: U+0042;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-C.ttf') format('truetype');
    unicode-range: U+0043;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-D.ttf') format('truetype');
    unicode-range: U+0044;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-E.ttf') format('truetype');
    unicode-range: U+0045;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-F.ttf') format('truetype');
    unicode-range: U+0046;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-G.ttf') format('truetype');
    unicode-range: U+0047;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-H.ttf') format('truetype');
    unicode-range: U+0048;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-I.ttf') format('truetype');
    unicode-range: U+0049;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-J.ttf') format('truetype');
    unicode-range: U+004A;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-K.ttf') format('truetype');
    unicode-range: U+004B;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-L.ttf') format('truetype');
    unicode-range: U+004C;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-M.ttf') format('truetype');
    unicode-range: U+004D;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-N.ttf') format('truetype');
    unicode-range: U+004E;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-O.ttf') format('truetype');
    unicode-range: U+004F;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-P.ttf') format('truetype');
    unicode-range: U+0050;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-Q.ttf') format('truetype');
    unicode-range: U+0051;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-R.ttf') format('truetype');
    unicode-range: U+0052;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-S.ttf') format('truetype');
    unicode-range: U+0053;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-T.ttf') format('truetype');
    unicode-range: U+0054;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-U.ttf') format('truetype');
    unicode-range: U+0055;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-V.ttf') format('truetype');
    unicode-range: U+0056;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-W.ttf') format('truetype');
    unicode-range: U+0057;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-X.ttf') format('truetype');
    unicode-range: U+0058;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-Y.ttf') format('truetype');
    unicode-range: U+0059;
}
@font-face {
    font-family: 'Yinit';
    src: url('/static/font/Yinit-Z.ttf') format('truetype');
    unicode-range: U+005A;
}
```

This means only 4-7kb (uncompressed) has to be downloaded for each page which is *much* more doable and represents a bandwidth reduction of ~100x for pages using 1 initial.

I don't know how font packaging or CTAN works, but it would be nice if these could be provided somehow so other people than me could benefit from the `yinit` initials. (As I said, I really like them and think it's a pity that they're hardly used, it looks like.)
